nodeLinker: node-modules
enableGlobalCache: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard

nmMode: hardlinks-local

# Allow modifications to the lockfile during CI builds
enableImmutableInstalls: false

# Prevent peer dependency warnings
enableStrictPeerDependencies: false
