nodeLinker: node-modules
enableGlobalCache: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard

nmMode: hardlinks-local

# Allow modifications to the lockfile during CI builds
immutablePatterns: []

# Use update-lockfile mode for CI builds
preferInteractive: false
enableTelemetry: false
