# Cloudflare Pages configuration

[build]
command = "bash ./scripts/cloudflare-install.sh"
publish = ".vercel/output/static"

[build.environment]
NODE_VERSION = "20.19.5"
NPM_FLAGS = "--legacy-peer-deps"

[compatibility]
nodejs_compat = true
