name = "next-on-cloudflare"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Necessary for Cloudflare Pages to recognize Node.js compatibility
[build.environment]
NODE_VERSION = "20.19.5"

[build]
command = "bash ./scripts/cloudflare-install.sh"

[site]
wrangler_config_path = "wrangler.toml"
