# Cloudflare Pages configuration
# This file configures the build process for Cloudflare Pages

[build]
  command = "bash ./scripts/cloudflare-install.sh"
  publish = ".vercel/output/static"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps --strict-false"

[compatibility]
  nodejs_compat = true
